#include "{{header_path}}"

namespace serial {
	{% for version in versions %}
	namespace {{version.namespace_str}} {
		{% for e in version.enums %}
		/**** {{e.name}} ****/

		const char *{{e.name}}_str({{e.name}} val) {
			switch (val) {
				{% for enumerator in e.enumerators %}
				case {{e.name}}::{{enumerator.name}}:
					return "{{enumerator.name}}";
				{% endfor %}
				default:
					return "_UNKNOWN_";
			}
		};
		{% endfor %}

		{% for b in version.bitfields %}
		/**** {{b.name}} ****/

		std::ostream &print_{{b.name}}(std::ostream &os, {{b.name}} const &val) {
			const char *frag = "";
			{% for f in b.fields %}
			if (val.{{f.name}}) {
				os << frag << "{{f.name}}";
				frag = " | ";
			}
			{% endfor %}
			return os;
		};
		{% endfor %}

		{% for s in version.structs %}
		/**** Transactions for {{s.name}} ****/
		{% for f in s.fields %}
		{% if f.is_optional %}
		bool {{s.name}}::has_{{f.name}}() const {
			return _{{f.name}}.has_value();
		}
		{% endif %}


		{% if f.is_primitive || f.is_optional %}
		{{s.name}}::{{f.set_trans_name}}::{{f.set_trans_name}}({{f.type_str}} const &value): _value(value) {}

		Transaction::Ptr {{s.name}}::{{f.set_trans_name}}::create({{f.type_str}} const &value) {
			return Ptr(new {{f.set_trans_name}}(value));
		}

		Transaction::Ptr {{s.name}}::{{f.set_trans_name}}::apply(Object &obj) {
			log_assert(
				obj.type_id() == TYPE_ID,
				util::f("Expecting object of type {{f.type_str}} but got ", obj.type_str())
			);

			{{s.name}} &cast_obj = static_cast<{{s.name}}&>(obj);
			cast_obj._ignore_start();
			auto old_value = cast_obj.{{f.name}}();
			cast_obj.set_{{f.name}}(_value);
			cast_obj._ignore_end();

			return {{f.set_trans_name}}::create(old_value);
		}
		{% endif %}
		{% if !f.is_primitive %}
		{{s.name}}::{{f.mod_trans_name}}::{{f.mod_trans_name}}(Transaction::Ptr &&child_t): _child_t(std::move(child_t)) {}

		Transaction::Ptr {{s.name}}::{{f.mod_trans_name}}::create(Transaction::Ptr &&child_t) {
			return Ptr(new {{f.mod_trans_name}}(std::move(child_t)));
		}

		Transaction::Ptr {{s.name}}::{{f.mod_trans_name}}::apply(Object &obj) {
			log_assert(
				obj.type_id() == TYPE_ID,
				util::f("Expecting object of type {{f.type_str}} but got ", obj.type_str())
			);

			{{s.name}} &cast_obj = static_cast<{{s.name}}&>(obj);
			cast_obj._ignore_start();
			{% if f.is_optional %}
			log_assert(cast_obj._{{f.name}}.has_value(), "Must call has_{{f.name}} before accessing {{f.name}}");
			//auto t = {{f.mod_trans_name}}::create(_child_t->apply(cast_obj._{{f.name}}.value()));
			{% else %}
			//auto t = {{f.mod_trans_name}}::create(_child_t->apply(cast_obj._{{f.name}}));
			{% endif %}
			cast_obj._ignore_end();

			//return t;
			return nullptr;
		}
		{% endif %}

		{% endfor %}

		{%- macro set_elements(struct, should_move) %}
			{% for f in struct.fields %}
			{% if should_move %}
			_{{f.name}} = std::move(other._{{f.name}});
			{% else %}
			_{{f.name}} = other._{{f.name}};
			{% endif %}
			{% endfor %}

			{% for f in s.fields %}
			{% if !f.is_primitive %}
			{% if f.is_optional %}
			if (_{{f.name}}) {
				_adopt_child(&_{{f.name}}.value());
			}
			{% else %}
			_adopt_child(&_{{f.name}});
			{% endif %}
			{% endif %}
			{% endfor %}
			//Leave idx unchaged as the object is still at same index in parent
		{% endmacro%}

		{{s.name}}::{{s.name}}() {
			{% for f in s.fields %}
			{% if !f.is_primitive && !f.is_optional%}
			_set_idx(&_{{f.name}}, {{f.idx_name}});
			{% endif %}
			{% endfor %}
		}

		{{s.name}}::{{s.name}}({{s.name}} const &other) {
{{ set_elements(s, false) }}
		}

		{{s.name}}::{{s.name}}({{s.name}} &&other) {
{{ set_elements(s, true) }}
		}

		{{s.name}} &{{s.name}}::operator=({{s.name}} const &other) {
{{ set_elements(s, false) }}

			return *this;
		}

		{{s.name}} &{{s.name}}::operator=({{s.name}} &&other) {
{{ set_elements(s, true) }}

			return *this;
		}


		uint32_t {{s.name}}::type_id() const {
			return TYPE_ID;
		}

		const char *{{s.name}}::type_str() const {
		return "{{s.name}}";
		}

		/**** Properties for {{s.name}} ****/

		{% for f in s.fields %}
		{{f.non_opt_type_str}} const &{{s.name}}::{{f.name}}() const {
			{% if f.is_optional %}
			log_assert(_{{f.name}}.has_value(), "You must call has_{{f.name}} before getting it.");
			return _{{f.name}}.value();
			{% else %}
			return _{{f.name}};
			{% endif %}
		}

		{% if !f.is_primitive %}
		{{f.non_opt_type_str}} &{{s.name}}::{{f.name}}() {
			{% if f.is_optional %}
			log_assert(_{{f.name}}.has_value(), "You must call has_{{f.name}} before getting it.");
			return _{{f.name}}.value();
			{% else %}
			return _{{f.name}};
			{% endif %}
		}
		{% endif %}

		{% if f.is_primitive || f.is_optional %}
		void {{s.name}}::set_{{f.name}}({{f.type_str}} const &value) {
			_implicit_start();
			_add_transaction({{f.set_trans_name}}::create(_{{f.name}}));
			_{{f.name}} = value;
			_implicit_end();
		}
		{% endif %}
		{% if !f.is_primitive && f.is_optional %}
		void {{s.name}}::set_{{f.name}}({{f.non_opt_type_str}} &&value) {
			_implicit_start();
			_add_transaction({{f.set_trans_name}}::create(_{{f.name}}));
			_{{f.name}} = std::move(value);
			_implicit_end();
		}
		{% endif %}

		{% endfor %}
		{% endfor %}
	} /* {{version.namespace_str}} */
	{% endfor %}
}
