#pragma once

#include <cstdint>
#include <iostream>

#include "serial/Container.hpp"
#include "util/UIDList.hpp"
#include "serial/Object.hpp"

namespace serial {
	{% for version in versions %}
	namespace {{version.namespace_str}} {
		{% for e in version.enums %}
		/**** {{e.name}} ****/
		enum class {{e.name}}: uint8_t {
			{% for enumerator in e.enumerators %}
			{% if enumerator.has_value %}
			{{enumerator.name}} = {{enumerator.value}},
			{% else %}
			{{enumerator.name}},
			{% endif %}
			{% endfor %}
		};

		const char *{{e.name}}_str({{e.name}} val);
		{% endfor %}

		{% for b in version.bitfields %}
		/**** {{b.name}} ****/
		struct {{b.name}} {
			{% for f in b.fields %}
			bool {{f.name}}: 1;
			{% endfor %}
		};

		std::ostream &print_{{b.name}}(std::ostream &os, {{b.name}} const &val);
		{% endfor %}


		/**** Objects ****/

		{% for s in version.structs %}
		/**** {{s.name}} ****/
		class {{s.name}}: public {{s.base_class}} {
			public:
				static const uint32_t TYPE_ID = 1; // TODO

			{% for f in s.fields %}
			{% if f.is_primitive || f.is_optional %}
				class {{f.set_trans_name}}: public Transaction {
					public:
						{{f.set_trans_name}}({{f.type_str}} const &value);

						static Ptr create({{f.type_str}} const &value);

						Ptr apply(Object &obj);

					private:
						{{f.type_str}} _value;
				};
			{% endif %}
			{% if !f.is_primitive %}
				class {{f.mod_trans_name}}: public Transaction {
					public:
						{{f.mod_trans_name}}(Transaction::Ptr &&child_t);

						static Ptr create(Transaction::Ptr &&child_t);

						Ptr apply(Object &obj);

					private:
						Transaction::Ptr _child_t;
				};
			{% endif %}
			{% endfor %}

			{% for f in s.fields %}
				static constexpr uint32_t {{f.idx_name}} = {{f.idx}};
			{% endfor %}

			public:
				{{s.name}}();
				{{s.name}}({{s.name}} const &other);
				{{s.name}}({{s.name}} &&other);
				{{s.name}} &operator=({{s.name}} const &other);
				{{s.name}} &operator=({{s.name}} &&other);

				uint32_t type_id() const;
				const char *type_str() const;

			{% for f in s.fields %}
				{% if f.is_optional %}
				bool has_{{f.name}}() const;
				{% endif %}

				{{f.non_opt_type_str}} const &{{f.name}}() const;
				{% if !f.is_primitive %}
				{{f.non_opt_type_str}} &{{f.name}}();
				{% endif %}

				{% if f.is_primitive || f.is_optional %}
				void set_{{f.name}}({{f.type_str}} const &value);
				{% endif %}
				{% if !f.is_primitive && f.is_optional %}
				void set_{{f.name}}({{f.non_opt_type_str}} &&value);
				{% endif %}


			{% endfor %}
			private:
			{% for f in s.fields %}
				{{f.type_str}} _{{f.name}};
			{% endfor %}
		};

		{% endfor %}
	} /* {{version.namespace_str}} */
	{% endfor %}
}
