#version 450

layout(set = 0, binding = 0, rgba8) uniform image2D result;
layout(set = 0, binding = 1) uniform OverlayUniform {
/*OVERLAY_UNIFORM_CONTENT*/
} overlay_uniform;
layout(set = 0, binding = 2, r32ui) uniform uimage2D node_id;

void main() {
	vec4 color = imageLoad(result, ivec2(gl_GlobalInvocationID.xy));

	uvec4 node = imageLoad(node_id, ivec2(gl_GlobalInvocationID.xy));

	color.x += node.x * 0.1;

	imageStore(result, ivec2(gl_GlobalInvocationID.xy), color);
}
